spring:
  application:
    name: codegen-springboot-initializr

codegen:
  profiles:
    springboot-maven-java:
      template-base-path: springboot/maven/java/

      ordered-artifact-keys:
        - pom
        - maven-wrapper
        - gitignore
        - application-yaml
        - source-scaffolder
        - test-scaffolder
        - readme

      artifacts:
        pom:
          templates:
            - template: pom.xml.ftl
              output-path: pom.xml

        maven-wrapper:
          templates:
            - template: maven-wrapper.properties.ftl
              output-path: .mvn/wrapper/maven-wrapper.properties

        gitignore:
          templates:
            - template: .gitignore.ftl
              output-path: .gitignore

        application-yaml:
          templates:
            - template: application.yml.ftl
              output-path: src/main/resources/application.yml

        source-scaffolder:
          templates:
            - template: MainClass.java.ftl
              output-path: src/main/java

        test-scaffolder:
          templates:
            - template: MainClassTests.java.ftl
              output-path: src/test/java

        readme:
          templates:
            - template: README.md.ftl
              output-path: README.md

templating:
  encoding: UTF-8
  handler: RETHROW
  template-path: /templates
  cache-enabled: true
  cache-update-delay-ms: 60000


freemarker:
  encoding: UTF-8
  template-exception-handler: RETHROW_HANDLER
  template-path: /templates

maven:
  source-folder:
    src-main-java: src/main/java
    src-main-resources: src/main/resources
    src-test-java: src/test/java
    src-test-resources: src/test/resources
    src-gen-java: src/gen/java