spring:
  application:
    name: codegen-blueprint

codegen:
  profiles:
    spring-boot-maven-java:
      ordered-artifact-keys:
        - build-config
        - build-tool-files
        - ignore-rules
        - source-layout
        - app-config
        - main-source-entrypoint
        - test-source-entrypoint
        - architecture-governance
        - sample-code
        - project-documentation

      artifacts:
        build-config:
          template-base-path: springboot/maven/java/
          templates:
            - template: pom.xml.ftl
              output-path: pom.xml

        build-tool-files:
          template-base-path: springboot/maven/java/
          templates:
            - template: maven-wrapper.properties.ftl
              output-path: .mvn/wrapper/maven-wrapper.properties
            - template: mvnw.ftl
              output-path: mvnw
            - template: mvnw.cmd.ftl
              output-path: mvnw.cmd

        ignore-rules:
          template-base-path: springboot/java/
          templates:
            - template: gitignore.ftl
              output-path: .gitignore

        source-layout:
          templates: [ ]

        app-config:
          template-base-path: springboot/java/
          templates:
            - template: application.yml.ftl
              output-path: src/main/resources/application.yml

        main-source-entrypoint:
          template-base-path: springboot/java/
          templates:
            - template: MainClass.java.ftl
              output-path: src/main/java

        test-source-entrypoint:
          template-base-path: springboot/java/
          templates:
            - template: MainClassTests.java.ftl
              output-path: src/test/java

        architecture-governance:
          template-base-path: springboot/java/
          templates: [ ]

        sample-code:
          template-base-path: springboot/java/
          templates: [ ]

        project-documentation:
          template-base-path: springboot/java/
          templates:
            - template: README.md.ftl
              output-path: README.md


templating:
  encoding: UTF-8
  handler: RETHROW
  template-path: /templates
  cache-enabled: false